version: '3.1'
services:
  # MySQL Service
  db:
    build: ./docker/db/
    container_name: ${DB_CONTAINER_NAME}
    restart: unless-stopped
    tty: true
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - pop-scong-network
    volumes:
      - ./.tmp/db-data:/var/lib/mysql

# Docker Networks
networks:
  pop-scong-network:
    driver: bridge
